version: '3'

services:
  workspace:
    image: localhost:5000/lasuillard/libra:local
    build:
      context: .
      dockerfile: ./Dockerfile
      target: workspace
    environment:
      CONTAINER: 1
      RUST_BACKTRACE: 1
      OTEL_SDK_DISABLED: 'true'
      OTEL_SERVICE_NAME: 'Libra'
      DATABASE_URL: sqlite://db.sqlite3
    command: sleep infinity
    init: true
    extra_hosts:
      - host.docker.internal:host-gateway
